name: build-and-test

on: [push, pull_request]

jobs:
  build:
    strategy: 
      fail-fast: false
      matrix:
          STACK: ['/cvmfs/sw.hsf.org/key4hep/setup.sh',
                  '/cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh']
          OS: ['alma9',
               'ubuntu22']
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/key4hep/key4hep-images/${{ matrix.OS }}:latest
      volumes:
        - ${{ github.workspace }}:/Package
        - /cvmfs:/cvmfs
      ports:
        - 80
    steps:
    - uses: actions/checkout@v4
    - uses: cvmfs-contrib/github-action-cvmfs@v4
    - name: CMake Configure
      run: 'cd Package; \
           mkdir -p build install; \
           source ${{ matrix.STACK }}; \
           cd build; \
           cmake -DCMAKE_INSTALL_PREFIX=../install ..'
    - name: Compile and Install
      run: 'cd Package; \
           source ${{ matrix.STACK }}; \
           cd build; \
           make ral install'
    - name: Compile tests
      run: 'cd Package; \
           source ${{ matrix.STACK }}; \
           cd build; \
           make unittest'
    - name: Run unittest
      run: 'cd Package; \
           source ${{ matrix.STACK }}; \
           cd build; \
           ctest -R unittest'
    - name: Run integration tests
      run: 'cd Package; \
           source ${{ matrix.STACK }}; \
           cd build; \
           ctest -R integration'
